"""
Django settings for sisa project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
from .base import *


BASE_DIR = Path(__file__).resolve().parent.parent
print (" develoment "+ str(BASE_DIR))
STATICFILES_DIRS = [Path.joinpath(BASE_DIR, 'static'), ]
STATIC_URL = '/static/'
ROOT_URLCONF = 'sisa.urls'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sk(uolwnvqf*d(k17&#enugr%$^fg)=z#)45^#v-ljwsyy!x1f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.100.8']



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'sisa',
        'USER': 'postgres',
        'PASSWORD': 'sisa',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'user_specific_db': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'sisa',  # Usa una plantilla de base de datos para crear bases de datos de usuarios
        'USER': 'your_db_admin_user',
        'PASSWORD': 'your_db_admin_password',
        'HOST': 'localhost',
        'PORT': '5432',
    },

}

